### STAGE 1:BUILD ###
FROM node:18.20.4-alpine3.20 AS build
# Create a Virtual directory inside the docker image
WORKDIR /dist/src/app
 
RUN npm cache clean --force
COPY . .
 
RUN npm install
RUN npm run build
 
### STAGE 2:RUN ###
 
FROM nginx:latest AS ngi
 
COPY --from=build /dist/src/app/dist/. /usr/share/nginx/html/
#COPY --from=build-common /dist/src/app/dist/container/. /usr/share/nginx/html/common
COPY --from=build /dist/src/app/src/nginx.conf  /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
EXPOSE 80