FROM node:20.18.2-alpine

WORKDIR /app

COPY . .

RUN npm install
RUN npm run postinstall

WORKDIR /app/shared
RUN npm  install
RUN npm run build

WORKDIR /app/hostels
RUN npm install
RUN npm run build

CMD [ "npm", "run", "start" ]