FROM node:22.11.0-alpine

WORKDIR /app

COPY ["package.json", "./"]

RUN npm install

COPY . .


WORKDIR /app/shared
RUN npm  install
RUN npm run build

WORKDIR /app/hostels
RUN npm install
RUN npm run build

CMD [ "npm", "run", "start" ]